spring.application.name=JavaSurveyApp
server.port=8080

# Firebird Database Connection
spring.datasource.url=jdbc:firebirdsql://localhost:3050/R:/DB/OPROS.FDB?charSet=UTF-8
spring.datasource.username=sysdba
spring.datasource.password=masterkey
spring.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver

# Hibernate settings
spring.jpa.database-platform=org.hibernate.community.dialect.FirebirdDialect
spring.jpa.hibernate.ddl-auto=update

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# Static Resources
spring.mvc.static-path-pattern=/static/**
