spring.application.name=JavaSurveyApp
server.port=8080

# Firebird Database Connection
spring.datasource.url=jdbc:firebirdsql://localhost:3050/R:/DB/OPROS.FDB?charSet=UTF-8
spring.datasource.username=sysdba
spring.datasource.password=masterkey
spring.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver
spring.jpa.database-platform=org.hibernate.dialect.FirebirdDialect

# Show SQL queries in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# Static Resources
spring.mvc.static-path-pattern=/static/**
