spring.application.name=JavaSurveyApp
server.port=8080

# Firebird Database Connection
# Using a path relative to the project directory
spring.datasource.url=jdbc:firebirdsql://localhost:3050/${user.dir}/OPROS.FDB?encoding=UTF8
spring.datasource.username=sysdba
spring.datasource.password=masterkey
spring.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver

# Hibernate settings
spring.jpa.database-platform=org.hibernate.community.dialect.FirebirdDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=false

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# Static Resources
spring.mvc.static-path-pattern=/static/**
